### ISSUE TITLE
Process input from HTML form fields such as text areas and option elements. Include at least one button.

### ISSUE THREAD

**Issue by GeoffreyEmerson** [GeoffreyEmerson/301-final-project#11]

**Comment by newcomercurt** [comment]
Got this working a bit already, but not done yet.

**Comment by CharlesEmrich** [comment]
Seems like we definitely have this? But it's not my topic area so I'm not going to close it.

**Comment by newcomercurt** [comment]
We do. I jusy wanted to wait to close it until the Ajax calls were working
