### ISSUE TITLE
Authenticate to a 3rd party

### ISSUE THREAD

**Issue by GeoffreyEmerson** [GeoffreyEmerson/301-final-project#17]
Include a server-side app that authenticates to a 3rd party server (such as FB, Yelp, or GitHub). Must use a 3rd party server that is significantly relevant to your project. You can use a server such as a weather information server, Yelp, Google (e.g., maps or streetview), Facebook, etc.

**Comment by newcomercurt** [comment]
Believe this is accomplished with google maps api
