### ISSUE TITLE
Extra Credit: Persist at least some of your app's data in two or more WebSQL tables and make SQLite queries that use joins/relations to filter data.

### ISSUE THREAD

**Issue by GeoffreyEmerson** [GeoffreyEmerson/301-final-project#23]

**Comment by GeoffreyEmerson** [comment]
I hope using Mongo qualifies for this.

**Comment by a-she** [comment]
Not clear on whether you used joins. Can you list specific line numbers of code in your server code that implements the equivalent of joins or relations?

**Comment by GeoffreyEmerson** [comment]
https://github.com/GeoffreyEmerson/301-final-project/blob/master/src/models/rsvp.js
Lines 5 and 6 are the equivalent of foreign keys.

https://github.com/GeoffreyEmerson/301-final-project/blob/master/src/api/rsvps.js
Line 63, the populate method when combined with the pseudo-foreign keys will essentially left join on those keys.

**Comment by a-she** [comment]
Ok, cool - thanks!
