### ISSUE TITLE
Determine how plotly handles two traces on a single heatmap

### ISSUE THREAD

**Issue by GeoffreyEmerson** [GeoffreyEmerson/301-final-project#48]
Possible functionality for mouseover to show user their choices.
Otherwise figure out how to do it with jQuery.

**Comment by CharlesEmrich** [comment]
Investigated this. Conclusion is: "badly."

I'm going to experiment a little bit with D3, but suspect that this particular route may be a non-starter.

**Comment by CharlesEmrich** [comment]
Plotly sucks, moved to highcharts
